### ISSUE TITLE
Add gtk-doc-tools to dependencies

### ISSUE THREAD

**Issue by denesb** [acrisci/i3ipc-glib#16]
autogen.sh will halt instantly if it is not present.

**Comment by denesb** [comment]
I mean add it to the README.md dependencies list.

**Comment by mtalexan** [comment]
Also, `gobject-introspection` isn't optional, despite what the README.md currently says.

**Comment by acrisci** [comment]
I'm going to redo the build system and fix that. Thanks for reporting.

**Comment by acrisci** [comment]
Closing this in favor of #23
