### ISSUE TITLE
!! File project.h missing !!

### ISSUE THREAD

**Issue by saulocastelo** [acrisci/i3ipc-glib#26]
@acrisci  I think you forgot to commit the project.h file.
https://github.com/acrisci/i3ipc-glib/blob/0a0564870ddf2bebf62f2ce3610676059ece8d90/i3ipc-glib/i3ipc-enum-types.h.in#L5

It's not building ...  Latest version ok: https://github.com/acrisci/i3ipc-glib/commit/83e432c6cd18c58b568ad6394c05340f2137a814

Thanks #

**Comment by acrisci** [comment]
Oops I forgot people primarily build this from master.

I'm updating to the meson build system and changed some stuff.

I'll fix this later today.

**Comment by saulocastelo** [comment]
Thanks :)
