### ISSUE TITLE
"urgent" event: only generated if a workspace becomes urgent but not the other way?

### ISSUE THREAD

**Issue by xuhdev** [acrisci/i3ipc-glib#3]
It's probably useful if an event is generated when a workspace becomes non-urgent.

I'm currently using [xfce4-i3-workspace-plugin](https://github.com/denesb/xfce4-i3-workspaces-plugin), but the plugin won't know when I un-urgent the currently focused workspace, that is, the workspace button is still shown as red unless I focus on a different workspace and come back.

**Comment by acrisci** [comment]
I just tested it with the python bindings and I get the workspace::urgent event both when the window becomes urgent and when it loses urgent status.

**Comment by denesb** [comment]
I can confirm that the urgent event is generated in both cases.

**Comment by acrisci** [comment]
Ok seems like it works ok.
