### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by cornerman** [acrisci/i3ipc-glib#4]
The deco_rect and focus properties are crucial for an application I am currently writing: https://github.com/cornerman/i3-easyfocus.

Would be great if there was a release I could depend on.

**Comment by acrisci** [comment]
Is it ready for release? Any bugs or issues you know of?

**Comment by cornerman** [comment]
Not that I know of, it works nicely.

**Comment by acrisci** [comment]
I'll do the release tomorrow, but I'm not doing any AUR updates until the new interface comes out next week. Use `i3ipc-glib-git` until then if you are distributing on archlinux.

**Comment by cornerman** [comment]
Thanks and sorry for the misunderstanding, I was not talking about releasing my tool in the near future. I just wanted to make sure, people can use it properly if they installed i3ipc-glib via their repository.

**Comment by acrisci** [comment]
Fixed in 2d59487
